on:
  workflow_dispatch:
  push:
    branches: test-consolpa4

jobs:
  job1:
    runs-on: windows-latest
    steps:
    - name: checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 1
        show-progress: false
    - name: build runtime
      run: |
        .\build.cmd -c Release -subset clr+libs+libs.tests
    - name: build TestConsolePalWindows3
      run: .\.dotnet\dotnet.exe build .\TestConsolePalWindows3\TestConsolePalWindows3.csproj -c Release
    - name: run TestConsolePal3
      run: |
        Set-Clipboard "u{263a}"        
        .\artifacts\bin\testhost\net9.0-windows-Release-x64\shared\Microsoft.NETCore.App\9.0.0\corerun.exe .\TestConsolePalWindows3\bin\Release\net8.0-windows\TestConsolePalWindows3.dll
