on:
  workflow_dispatch:

jobs:
  job1:
    runs-on: windows-latest
    steps:
    - name: checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 1
        show-progress: false
    - name: run
      run: |
        .\build.cmd -c Release -subset clr+libs+libs.tests
